set(CMAKE_SYSTEM_NAME Windows)

find_program(CLANG_EXECUTABLE NAMES clang.exe clang REQUIRED)
find_program(CLANGXX_EXECUTABLE NAMES clang++.exe clang++ REQUIRED)
find_program(LLVM_AR_EXECUTABLE NAMES llvm-ar.exe llvm-ar REQUIRED)
find_program(LLVM_RANLIB_EXECUTABLE NAMES llvm-ranlib.exe llvm-ranlib REQUIRED)
find_program(LLVM_NM_EXECUTABLE NAMES llvm-nm.exe llvm-nm REQUIRED)
find_program(LLVM_LIB_EXECUTABLE NAMES llvm-lib.exe llvm-lib)
find_program(NINJA_EXECUTABLE NAMES ninja.exe ninja REQUIRED)

set(CMAKE_C_COMPILER "${CLANG_EXECUTABLE}" CACHE FILEPATH "" FORCE)
set(CMAKE_CXX_COMPILER "${CLANGXX_EXECUTABLE}" CACHE FILEPATH "" FORCE)

set(CMAKE_C_COMPILER_AR "${LLVM_AR_EXECUTABLE}" CACHE FILEPATH "" FORCE)
set(CMAKE_C_COMPILER_RANLIB "${LLVM_RANLIB_EXECUTABLE}" CACHE FILEPATH "" FORCE)
set(CMAKE_C_COMPILER_NM "${LLVM_NM_EXECUTABLE}" CACHE FILEPATH "" FORCE)
set(CMAKE_CXX_COMPILER_AR "${LLVM_AR_EXECUTABLE}" CACHE FILEPATH "" FORCE)
set(CMAKE_CXX_COMPILER_RANLIB "${LLVM_RANLIB_EXECUTABLE}" CACHE FILEPATH "" FORCE)
set(CMAKE_CXX_COMPILER_NM "${LLVM_NM_EXECUTABLE}" CACHE FILEPATH "" FORCE)
set(CMAKE_RANLIB "${LLVM_RANLIB_EXECUTABLE}" CACHE FILEPATH "" FORCE)
set(CMAKE_NM "${LLVM_NM_EXECUTABLE}" CACHE FILEPATH "" FORCE)

set(CMAKE_AR "${LLVM_AR_EXECUTABLE}" CACHE FILEPATH "" FORCE)
set(CMAKE_C_ARCHIVE_CREATE "<CMAKE_AR> rcs <TARGET> <OBJECTS>" CACHE STRING "" FORCE)
set(CMAKE_C_ARCHIVE_FINISH "" CACHE STRING "" FORCE)
set(CMAKE_CXX_ARCHIVE_CREATE "<CMAKE_AR> rcs <TARGET> <OBJECTS>" CACHE STRING "" FORCE)
set(CMAKE_CXX_ARCHIVE_FINISH "" CACHE STRING "" FORCE)

set(CMAKE_MAKE_PROGRAM "${NINJA_EXECUTABLE}" CACHE FILEPATH "" FORCE)
