set(CMAKE_SYSTEM_NAME Linux)

set(CMAKE_C_COMPILER clang CACHE FILEPATH "" FORCE)
set(CMAKE_CXX_COMPILER clang++ CACHE FILEPATH "" FORCE)

set(CMAKE_C_COMPILER_AR llvm-ar CACHE FILEPATH "" FORCE)
set(CMAKE_C_COMPILER_RANLIB llvm-ranlib CACHE FILEPATH "" FORCE)
set(CMAKE_C_COMPILER_NM llvm-nm CACHE FILEPATH "" FORCE)
set(CMAKE_CXX_COMPILER_AR llvm-ar CACHE FILEPATH "" FORCE)
set(CMAKE_CXX_COMPILER_RANLIB llvm-ranlib CACHE FILEPATH "" FORCE)
set(CMAKE_CXX_COMPILER_NM llvm-nm CACHE FILEPATH "" FORCE)
